[package]
name = "day_8"
version = "0.1.0"
authors = ["gitAdrianK <14051526+gitAdrianK@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.4.2"
